# Generated by Django 6.0.7 on 2026-07-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='person_audio/', verbose_name='التسجيل الصوتي'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='phrase_audio/', verbose_name='التسجيل الصوتي'),
        ),
    ]
